[package]
name = "outlookfix"
version = "0.1.0"
authors = ["lolface"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winreg = "0.7"
encoding_rs = "0.8.23"
encoding_rs_io = "0.1.7"